products/urls.py
from django.urls import path
from . import views

 
app_name = 'products'

urlpatterns = [
    path('search/', views.search_result, name='search_result'),
    path('', views.products, name='products'),
    path('shop.html/', views.cartpage, name = 'shop'),
]

productsdetails/urls.py
from django.urls import include, path
from . import views

app_name = 'productsdetails'

urlpatterns = [
    path('<int:pk>/', views.productsdetails, name='details'),
    path('product/get/<int:id>', views.getProduct, name='get_product'),
    path('coupon/search/', views.coupon, name='coupon'),
    path('coupon/apply/', views.apply, name='apply'),
    path('MyCart/', views.MyCart, name='MyCart'),
    path('addItem/', views.itemtocart, name='additem')
]

tugas1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('promotions/', include('promotions.urls')),
    path('productsdetails/', include('productsdetails.urls')),
	path('reviews/', include('reviews.urls')),
    path('products/', include('products.urls')),
	path('accounts/', include('authentication.urls')),
    path('fast_transaction/', include('fast_transaction.urls')),
]

products/models.py
from django.db import models

class Products(models.Model) :
    gambar = models.URLField(max_length=300, null=True)
    namaBarang = models.CharField(max_length = 50)
    harga = models.DecimalField(decimal_places=2, max_digits=12)
    stok = models.PositiveIntegerField()
    deskripsi = models.CharField(max_length = 200)

    def __str__(self):
        return self.namaBarang

# class Keranjang(models.Model) :
#     gambar = models.URLField(max_length=300, null=True)
#     title = models.CharField(max_length = 50)
#     desc = models.CharField(max_length = 200)

products/forms.py
from django import forms
# from .models import Products
# # Create your views here.

# class Pencarian(forms.ModelForm):
#     class Meta:
#         model = Products
#         fields = "__all__"
    
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field in iter(self.fields):
#             self.fields[field].widget.attrs.update({
#                 'class': 'form-control'
#         }
#         )

products/views.py
from django.shortcuts import render
from .models import Products
# Create your views here.
def products(request):
    cari = Products.objects.all()
    context = {
        'cari':cari
    }
    return render(request, 'test.html', context)

def search_result(request):
    produk = request.GET.get("hasil_cari")
    cari = Products.objects.filter(namaBarang__icontains=produk)
    context = {
        'cari':cari
    }
    return render(request, 'test.html', context)

def cartpage(request):
    return render(request,'shop.html')

products/templates/shop.html
<!DOCTYPE html>
{% load static %}
{% include 'base.html' %}
{% include 'navbar.html' %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'style1.css' %}">
    <class="cart">
    </class>
</head>
<body>
<div class="products-container">
    <div class="product-header" style="color: white;">
        <h5 class="product-title" style="text-align: center;">PRODUCT</h5>
        <br><br>
        <!-- <h5 class="quantity">QUANTITY</h5> -->
    </div>
    <div class="products">
    </div>
</div>
<script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
<script src="{% static 'shopcart.js'%}"></script>

</body>
</html>

products/templates/test.html
<!DOCTYPE html>
{% load static %}
{% include 'base.html' %}
{% include 'navbar.html' %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'style1.css' %}">
    <title>Products</title>
    <class="cart">
            <a href="shop.html">
             <button class="btn btn-success"><ion-icon name="basket"></ion-icon>Cart</button>
            </a>
    </class>
</head>
<body>
    <div class="container search d-flex justify-content-center">
        <form class="form-inline" action="{% url 'products:search_result' %}">
            <input name="hasil_cari" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button>
          </form>
    </div>
    
    <div class="row row-cols-1 row-cols-md-4 rapi">
        {% for jenis in cari %}
        <div class="col mb-4 d-flex justify-content-center">
          <div class="card">
            <img src="{{ jenis.gambar }}" class="card-img-top" alt="kaos">
            <div class="card-body">
              <h5 class="card-title" id="nama"><a href="{% url 'productsdetails:details' jenis.id %}">{{jenis.namaBarang}}</a></h5>
              <p class="card-text" id="harga">Rp{{ jenis.harga }},-</p>
              <button class="btn btn-primary">Add to Cart</button>
            </div>
          </div>
        </div>
    {% endfor %}
    <script src="https://unpkg.com/ionicons@5.0.0/dist/ionicons.js"></script>
    <script src="{% static 'shopcart.js'%}"></script>
  </body>
</html>