authentication/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('logged_out/', views.logged_out, name='logged_out'),
    path('', views.accounts, name='accounts'),
    path('', include('django.contrib.auth.urls')),
    path('', include('allauth.urls')),
    path('register/', views.register, name='register'),
    path('registered/', views.registered, name='registered'),
]

fast_transaction/urls.py
from django.urls import path
from . import views

app_name = 'fast_transaction'

urlpatterns = [
    path('bertransaksi/', views.bertransaksi, name="bertransaksi"),
    path("cek_transaksi/", views.cek_transaksi, name="cek_transaksi"),
    path("historyKamu/", views.history_user, name="history_user"),
    path('coupon/search/', views.coupon, name='coupon'),
    path('coupon/apply/', views.apply, name='apply'),
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'


urlpatterns = [
    path('', views.index, name='index'),
    # dilanjutkan ...
]

products/urls.py
from django.urls import path
from . import views

 
app_name = 'products'

urlpatterns = [
    path('search/', views.search_result, name='search_result'),
    path('', views.products, name='products'),
    path('shop.html/', views.cartpage, name = 'shop'),
]

productsdetails/urls.py
from django.urls import include, path
from . import views

app_name = 'productsdetails'

urlpatterns = [
    path('<int:pk>/', views.productsdetails, name='details'),
    path('product/get/<int:id>', views.getProduct, name='get_product'),
    path('coupon/search/', views.coupon, name='coupon'),
    path('coupon/apply/', views.apply, name='apply'),
    path('MyCart/', views.MyCart, name='MyCart'),
    path('addItem/', views.itemtocart, name='additem')
]

promotions/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.promotions_view, name='promotions_view'),
    path('search/', views.search_result_view, name='search_result')
    
]

reviews/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.review, name='review'),
]

transactions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.transactions_view, name="transactions_view"),
]

tugas1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('promotions/', include('promotions.urls')),
    path('productsdetails/', include('productsdetails.urls')),
	path('reviews/', include('reviews.urls')),
    path('products/', include('products.urls')),
	path('accounts/', include('authentication.urls')),
    path('fast_transaction/', include('fast_transaction.urls')),
]

homepage/models.py
from django.db import models

# Create your models here.

keranjang/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Products

# Create your models here.
class Transaction(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    total = models.PositiveIntegerField()

    def __str__(self):
        return self.product.namaBarang

class Keranjang(models.Model):
    kepunyaan_keranjang = models.OneToOneField(User, on_delete=models.CASCADE)
    dalam_keranjang = models.ManyToManyField(Transaction)

    def __str__(self):
        return self.nama_keranjang.username

products/models.py
from django.db import models

class Products(models.Model) :
    gambar = models.URLField(max_length=300, null=True)
    namaBarang = models.CharField(max_length = 50)
    harga = models.DecimalField(decimal_places=2, max_digits=12)
    stok = models.PositiveIntegerField()
    deskripsi = models.CharField(max_length = 200)

    def __str__(self):
        return self.namaBarang

# class Keranjang(models.Model) :
#     gambar = models.URLField(max_length=300, null=True)
#     title = models.CharField(max_length = 50)
#     desc = models.CharField(max_length = 200)

promotions/models.py
from django.db import models

# Create your models here.
class Coupon(models.Model):
    code = models.CharField(max_length = 30)
    periode = models.DateTimeField()
    percent_discount = models.IntegerField(
        default=0,
     )
    description = models.TextField(max_length=200)

    def __str__(self):
        return self.code

reviews/models.py
from django.db import models
from products.models import Products

RATING = [
	("1", "1 - Terrible"),
	("2", "2 - Poor"),
	("3", "3 - Ok"),
	("4", "4 - Good"),
	("5", "5 - Excellent")
]

class Review(models.Model):
	name = models.CharField(max_length = 64)
	product = models.ForeignKey(Products, on_delete=models.CASCADE)
	rating = models.CharField(max_length = 64, choices=RATING)
	review = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

transactions/models.py
from django.db import models


# Create your models here.

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(max_length=254, required=True)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

products/forms.py
from django import forms
# from .models import Products
# # Create your views here.

# class Pencarian(forms.ModelForm):
#     class Meta:
#         model = Products
#         fields = "__all__"
    
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field in iter(self.fields):
#             self.fields[field].widget.attrs.update({
#                 'class': 'form-control'
#         }
#         )

reviews/forms.py
from django import forms
from .models import Review
from products.models import Products 

class ReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		exclude = ["name", "date"]
		widgets = {
			'review': forms.Textarea(attrs={'class':'responsive-text-area'})
				}

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

keranjang/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.shortcuts import render
from .models import Products
# Create your views here.
def products(request):
    cari = Products.objects.all()
    context = {
        'cari':cari
    }
    return render(request, 'test.html', context)

def search_result(request):
    produk = request.GET.get("hasil_cari")
    cari = Products.objects.filter(namaBarang__icontains=produk)
    context = {
        'cari':cari
    }
    return render(request, 'test.html', context)

def cartpage(request):
    return render(request,'shop.html')

promotions/views.py
from django.shortcuts import render
from django.db.models import Q

from .models import Coupon

# Create your views here.
def promotions_view (request):
    coupons = Coupon.objects.all()
    
    context = {
        'coupons' : coupons,
    }
    return render (request, 'promotions.html', context)

def search_result_view (request):
    query = request.GET.get('input')
    dropdown = request.GET.get('dropdown')
    not_int_input = False
    if dropdown == 'kode':
        coupons = Coupon.objects.filter(code__icontains=query)
    else:
        try:
            coupons = Coupon.objects.filter(percent_discount__gte = query)
        except:
            not_int_input = True
            return render(request,'promotions.html',{'not_int_input':not_int_input})
            

    context = {
        'coupons' : coupons,
        'not_int_input': not_int_input,
    }
    return render (request, 'promotions.html', context)

reviews/views.py
from django.shortcuts import render
from .models import Review
from .forms import ReviewForm


def review(request):
    
    if(request.method == 'POST'):
        form = ReviewForm(request.POST or None)
        response = {}
        if form.is_valid():
            f = form.save(commit=False)
            f.name = request.user.username
            f.save()
            response['form'] = f
            return render(request, 'thankyou.html', response)
    else:
        form = ReviewForm()
        return render(request, 'reviews.html', {'form':form})

transactions/views.py
from django.shortcuts import render
from .models import Transactions

# Create your views here.

def transactions_view(request):
    transactions = Transactions.objects.all()

    context = {
        'transactions' : transactions,
    }
    return render(request,'transactions.html',context)

homepage/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
    crossorigin="anonymous">
  </head>
  <body>
    {% block content %}
    <!--Isi Page-->
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" 
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" 
    crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" 
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" 
    crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" 
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" 
    crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/index.html
<!DOCTYPE html>
{% load static %}
{% include "base.html" %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Beranda</title>
</head>
<body>
    <h1 class="beranda beranda-h1">WELCOME TO <br> PEPEW</h1>
    <div class="container beranda beranda-navbar">
        <div class="row">
          <div class="col"><a href="{% url 'products:products' %}">Products</a></div>
            {% if user.is_authenticated %}
              <div class="col"><a href=transactions>Transactions</a></div>
              <div class="col"><a href=promotions>Promotions</a></div>
              <div class="col"><a href=reviews>Reviews</a></div>
            {% else %}
                <div class="col"><a href="{% url 'login' %}">Login</a></div>
                <div class="col"><a href="{% url 'register' %}">Register</a></div>
            {% endif %}
        </div>
      </div>
</body>
</html>

homepage/templates/navbar.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'homepage:index' %}">Pepew</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" 
        aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'products:products' %}">Products<span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href=/transactions>Transactions</a>
            <a class="nav-item nav-link" href=/promotions>Promotions</a>
            <a class="nav-item nav-link" href=/reviews>Reviews</a>
            
            {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'logout'%}?next=/accounts/logged_out/">Logout</a>
            {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
            
        </div>
        </div>
    </nav>
</body>
</html>

promotions/templates/promotions.html
<!DOCTYPE html>
{% load static %}
{% include "base.html" %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'promotions-style.css' %}">
    <title>Promotions</title>
</head>
<body class="container-body">
    {% include "navbar.html" %}

    <h1 class="promotions-header">PROMOTIONS</h1>

        <form action="{% url 'search_result' %}" method="get" class="form-inline d-flex justify-content-center md-form form-sm">
          <select name="dropdown" class="custom-select my-1 mr-sm-2" id="">
            <option value="kode">kode</option>
            <option value="diskon">% diskon</option>
          </select>
          <input name="input" class="form-control form-control-sm mr-3 w-25" type="text" placeholder="Search"
            aria-label="Search">
          <div class="search-button">
          <button class="btn" ><i class="fa fa-search" aria-hidden="true"></i></button>
          </div>
        </form>

    {% if not_int_input %}
        <h4 class="p-3 text-center text-light text-bold">Masukkan pencarian diskon dengan benar</h4>
    {% endif %}

    <div class="table-body">
    <table class="table coupons-table">
        <thead class="coupons-thead" >
          <tr>
            <th scope="col">Kode</th>
            <th scope="col">Periode</th>
            <th scope="col">Diskon</th>
            <th scope="col">Deskripsi</th>
          </tr>
        </thead>
        {% for i in coupons %}
        <tbody class="body-table">
          <tr>
            <th scope="row">{{i.code}}</th>
            <td>{{i.periode}}</td>
            <td>{{i.percent_discount}}%</td>
            <td>{{i.description}}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
    </div>
      


</body>
</html>

transactions/templates/transactions.html
<!DOCTYPE html>
{% load static %}
{% include "base.html" %}
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'transactions-style.css' %}">
    <title>Transactions</title>
</head>
<body class="container-body">
    {% include "navbar.html" %}

    <h1 class="promotions-header">TRANSACTIONS HISTORY</h1>
  <div class="table-responsive">
    <div class="table-body">
    <table class="table coupons-table">
        <thead class="coupons-thead" >
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Buyer</th>
            <th scope="col">Purchase Date</th>
            <th scope="col">Coupon</th>
            <th scope="col">Total</th>
          </tr>
        </thead>
        {% for i in transactions %}
        <tbody class="body-table">
          <tr>
            <th scope="row">{{i.product}}</th>
            <td>{{i.buyer}}</td>
            <td>{{i.purchase_date}}</td>
            <td>{{i.coupon}}</td>
            <td>Rp.{{i.total}}</td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
    </div>
  </div>


</body>
</html>